apiVersion: v1
kind: List
items:
- apiVersion: tsb.tetrate.io/v2
  kind: Tenant
  metadata:
    name: flagger
    annotations: 
      tsb.tetrate.io/organization: tetrate
  spec:
    displayName: flagger
- apiVersion: tsb.tetrate.io/v2
  kind: Workspace
  metadata:
    name: bookinfo-ws
    annotations: 
      tsb.tetrate.io/organization: tetrate
      tsb.tetrate.io/tenant: flagger
  spec:
    namespaceSelector:
      names:
        - "app-cluster-1/flagger-*"
- apiVersion: gateway.tsb.tetrate.io/v2
  kind: Group
  metadata:
    name: bookinfo-gateway
    annotations:
      tsb.tetrate.io/organization: tetrate
      tsb.tetrate.io/tenant: flagger
      tsb.tetrate.io/workspace: bookinfo-ws
  spec:
    displayName: bookinfo-gateway-group
    namespaceSelector:
      names:
        - "app-cluster-1/flagger-*"
    configMode: DIRECT
- apiVersion: traffic.tsb.tetrate.io/v2
  kind: Group
  metadata:
    name: bookinfo-traffic
    annotations:
      tsb.tetrate.io/organization: tetrate
      tsb.tetrate.io/tenant: flagger
      tsb.tetrate.io/workspace: bookinfo-ws
  spec:
    displayName: bookinfo-traffic-group
    namespaceSelector:
      names:
        - "app-cluster-1/flagger-*"
    configMode: DIRECT
- apiVersion: security.tsb.tetrate.io/v2
  kind: Group
  metadata:
    name: bookinfo-security
    annotations:
      tsb.tetrate.io/organization: tetrate
      tsb.tetrate.io/tenant: flagger
      tsb.tetrate.io/workspace: bookinfo-ws
  spec:
    displayName: bookinfo-security-group
    namespaceSelector:
      names:
        - "app-cluster-1/flagger-bookinfo"
    configMode: DIRECT
- apiVersion: install.tetrate.io/v1alpha1
  kind: IngressGateway
  metadata:
    name: tsb-gateway-flagger-bookinfo
    annotations:
      cloud.google.com/load-balancer-type: "Internal"
  spec:
    kubeSpec:
      service:
        type: LoadBalancer
- apiVersion: networking.istio.io/v1alpha3
  kind: Gateway
  metadata:
    name: flagger-bookinfo-gateway
    labels:
      istio.io/rev: tsb
    annotations:
      tsb.tetrate.io/organization: tetrate
      tsb.tetrate.io/tenant: flagger
      tsb.tetrate.io/workspace: bookinfo-ws
      tsb.tetrate.io/gatewayGroup: bookinfo-gateway
  spec:
    selector:
      app: tsb-gateway-flagger-bookinfo
    servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
      - flagger-bookinfo.tetrate.com
- apiVersion: networking.istio.io/v1alpha3
  kind: DestinationRule
  metadata:
    name: productpage
    labels:
      istio.io/rev: tsb
    annotations:
      tsb.tetrate.io/organization: tetrate
      tsb.tetrate.io/tenant: flagger
      tsb.tetrate.io/workspace: bookinfo-ws
      tsb.tetrate.io/trafficGroup: bookinfo-traffic
  spec:
    host: productpage
    subsets:
    - name: v1
      labels:
        version: v1
- apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  metadata:
    name: bookinfo
    labels:
      istio.io/rev: tsb
    annotations:
      tsb.tetrate.io/organization: tetrate
      tsb.tetrate.io/tenant: flagger
      tsb.tetrate.io/workspace: bookinfo-ws
      tsb.tetrate.io/gatewayGroup: bookinfo-gateway
  spec:
    hosts:
      - "flagger-bookinfo.tetrate.com"
    gateways:
      - flagger-bookinfo-gateway
    http:
    - match:
      - uri:
          exact: /productpage
      - uri:
          prefix: /static
      - uri:
          exact: /login
      - uri:
          exact: /logout
      - uri:
          prefix: /api/v1/products
      route:
      - destination:
          host: productpage
          port:
            number: 9080
- apiVersion: networking.istio.io/v1alpha3
  kind: DestinationRule
  metadata:
    name: reviews
    labels:
      istio.io/rev: tsb
    annotations:
      tsb.tetrate.io/organization: tetrate
      tsb.tetrate.io/tenant: flagger
      tsb.tetrate.io/workspace: bookinfo-ws
      tsb.tetrate.io/trafficGroup: bookinfo-traffic
  spec:
    host: reviews
    subsets:
    - name: stable
      labels:
        app: reviews
- apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  metadata:
    name: reviews
    labels:
      istio.io/rev: tsb
    annotations:
      tsb.tetrate.io/organization: tetrate
      tsb.tetrate.io/tenant: flagger
      tsb.tetrate.io/workspace: bookinfo-ws
      tsb.tetrate.io/trafficGroup: bookinfo-traffic
  spec:
    hosts:
      - reviews
    http:
    - route:
      - destination:
          host: reviews
          subset: stable
        weight: 100
- apiVersion: networking.istio.io/v1alpha3
  kind: DestinationRule
  metadata:
    name: ratings
    labels:
      istio.io/rev: tsb
    annotations:
      tsb.tetrate.io/organization: tetrate
      tsb.tetrate.io/tenant: flagger
      tsb.tetrate.io/workspace: bookinfo-ws
      tsb.tetrate.io/trafficGroup: bookinfo-traffic
  spec:
    host: ratings
    subsets:
    - name: v1
      labels:
        version: v1
- apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  metadata:
    name: ratings
    labels:
      istio.io/rev: tsb
    annotations:
      tsb.tetrate.io/organization: tetrate
      tsb.tetrate.io/tenant: flagger
      tsb.tetrate.io/workspace: bookinfo-ws
      tsb.tetrate.io/trafficGroup: bookinfo-traffic
  spec:
    hosts:
    - ratings
    http:
    - route:
      - destination:
          host: ratings
          subset: v1
- apiVersion: networking.istio.io/v1alpha3
  kind: DestinationRule
  metadata:
    name: details
    labels:
      istio.io/rev: tsb
    annotations:
      tsb.tetrate.io/organization: tetrate
      tsb.tetrate.io/tenant: flagger
      tsb.tetrate.io/workspace: bookinfo-ws
      tsb.tetrate.io/trafficGroup: bookinfo-traffic
  spec:
    host: details
    subsets:
    - name: v1
      labels:
        version: v1
- apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  metadata:
    name: details
    labels:
      istio.io/rev: tsb
    annotations:
      tsb.tetrate.io/organization: tetrate
      tsb.tetrate.io/tenant: flagger
      tsb.tetrate.io/workspace: bookinfo-ws
      tsb.tetrate.io/trafficGroup: bookinfo-traffic
  spec:
    hosts:
    - details
    http:
    - route:
      - destination:
          host: details
          subset: v1
